kind: pipeline
name: default

steps:
- name: manifest
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    target: barakstout/arduino-delivery-container/bar:latest
    template: barakstout/arduino-delivery-container/bar:latest-ARCH
    platforms:
      - linux/amd64
      - linux/arm

---
kind: pipeline
name: arm

platform:
  os: linux
  arch: arm

steps:

- name: build arm
  image: plugins/docker
  settings:
    repo: barakstout/arduino-delivery-container
    auto_tag: true
    auto_tag_suffix: drone-arm
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: send
  image: plugins/webhook
  settings:
    urls:
      from_secret: notification_url

---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:

- name: build amd64
  image: plugins/docker
  settings:
    repo: barakstout/arduino-delivery-container
    auto_tag: true
    auto_tag_suffix: drone-amd64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: send
  image: plugins/webhook
  settings:
    urls:
      from_secret: notification_url
