---
kind: pipeline
name: default

steps:

- name: build
  image: docker
  environment:
    DOCKER_LOGIN:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  commands:
    - export DOCKER_CLI_EXPERIMENTAL=enabled
    - docker buildx create --name multibuilder
    - docker buildx use multibuilder
    - docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm/v6 -t barakstout/arduino-delivery-container:latest . --push

- name: send
  image: plugins/webhook
  settings:
    urls:
      from_secret: notification_url

# kind: pipeline
# name: amd64
#
# platform:
#   os: linux
#   arch: amd64
#
# steps:
#
# - name: build amd64
#   image: plugins/docker
#   settings:
#     repo: barakstout/arduino-delivery-container
#     auto_tag: true
#     auto_tag_suffix: drone-amd64
#     username:
#       from_secret: docker_username
#     password:
#       from_secret: docker_password
#
# - name: send
#   image: plugins/webhook
#   settings:
#     urls:
#       from_secret: notification_url
